# Custom Language File for Launcher Customizer

[ejs.app]
title = "CSMP Launcher"

[ejs.landing]
rickmediaURL = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
mediaDiscordURL = "https://discord.gg/FdKtzRQfhV"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le launcher du serveur CSMP!"
welcomeDescription = "Le serveur Minecraft CSMP est un serveur moddé communautaire pour le lycée George Clemenceau de Montpellier."
welcomeDescCTA = "Prêt à rejoindre ?"